inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'config/environments/test.rb'
    - 'vendor/**/*'

# because it's silly to care
Style/StringLiterals:
  Enabled: false
