- dor_wasSeedPreassemblyWF_build-was-seed-druid-tree
- dor_wasSeedPreassemblyWF_content-metadata-generator
- dor_wasSeedPreassemblyWF_desc-metadata-generator
- dor_wasSeedPreassemblyWF_thumbnail-generator
- dor_wasSeedPreassemblyWF_end-was-seed-preassembly

